### PR TITLE
User-Path limit

### PR DESCRIPTION
**Pull request by FraVieMor**
Per user and path limit commented in a previous PR (#36).

### CODE REVIEW

**Comment by FraVieMor** [comment]
I have had some free time to added e2e test :)

**Comment by wraithgar** [comment]
Extremely helpful! Thank you.  Thanks for your patience waiting for me to review this, sometimes it takes awhile for me to get around to some of these OSS libs.

If you would please go ahead and add a quick entry to the README adding this new option and the response headers I think this PR would be ready to ship!

**Comment by FraVieMor** [comment]
OK! Thank you. I will do that as soon as possible.

**Comment by wraithgar** [comment]
Had some free time today and went ahead and merged this and updated the README.

published as `v1.4.0`

**Pull request merged**
