### PR TITLE
Check Unauthorised from hapi authorization

### PR DESCRIPTION
**Pull request by Cheprer**
Added handler for event 'onPreResponse' to catch unauthorised from hapi
authorization.

### CODE REVIEW

**Comment by Cheprer** [comment]
#35

**Comment by wraithgar** [comment]
Wow, thank you for taking the time to make this PR, there's quite a bit here.  I don't have time this instant to review it but wanted to comment real quick to at least acknowledge that I've seen it and I will review it soon.

**Comment by wraithgar** [comment]
Thanks for your patience, I finally have some time to outline what I think is difficult about this bug:

Adding a check `onPreResponse` sort of defeats the purpose of having a rate limit on your handler, as that only fires after the handler itself runs.

What I think needs to happen is that the existing `onPostAuth` handler becomes an `onPreAuth`, and instead of calling `getUser` it just uses the ip of the request.

Then a new `onPostAuth` handler should somehow re-check if the user is authenticated, and if they are recalculate the limit. Here is where it gets tricky however.  If the user is not authenticated, whatever the preAuth handler did should hold. If they are authenticated, the new limit based on user and not IP should take over.  Unfortunately this means there is no way to rate limit the physical act of validating the auth.  Perhaps this is acceptable, I don't know.

**Comment by wraithgar** [comment]
Perhaps it is time to think about separating the idea of authorized and unauthorized requests.  As it stands now I don't see how I could limit a route based on IP only but not on authorized user (so to prevent brute force auth attempts but not to limit authenticated users in any way)

**Comment by Cheprer** [comment]
Separating these two makes sense. Would be nice to have that. Unfortunately I don't have much time now to rework it because it would be little bit bigger pr then this one. :)

**Comment by Cheprer** [comment]
@wraithgar will you have time to take a look at this please and if so when? much appreciated, Cheprer

**Pull request closed without merging**
