### PR TITLE
Stringify user cache key

### LINKED ISSUE #28: Invalid key error
When using catbox-memory with non-string user IDs an invalid key error is produced trying to read from the cache.

### PR DESCRIPTION
**Pull request by luckycadow**
Fixes #28 by ensuring user cache key is always a string

### CODE REVIEW

**Comment by wraithgar** [comment]
Thank you so much for submitting this PR.  This is the kind of bug I'd like to make sure we add a test for.  I'm more than willing to do so, but it will have to wait till Monday as I try not to do much work on the weekends.

The fix is great as-is, I'd just add a new `describe` block that returns the id as a Number and make sure it works generally.

**Comment by luckycadow** [comment]
How do you feel about adding a feature to apply rate limiting by route tag?  I'd be happy to open another PR for it.  I'm using this plugin for a swagger documented api and I'd like to prevent rate limiting from being applied to the swagger-ui routes, which are defined by a plugin so I don't have access to their config to disable rate limiting that way.

**Comment by wraithgar** [comment]
A tag-based filter feels like a very natural iteration on this that's very within the "hapi" approach.

**Comment by wraithgar** [comment]
Published as `v1.3.1`

**Pull request merged**
